# Generated by Django 5.2.13 on 2026-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbCrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, verbose_name='项目ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('url', models.CharField(max_length=500, verbose_name='爬取URL')),
                ('env_id', models.IntegerField(blank=True, null=True, verbose_name='环境ID')),
                ('credential_id', models.IntegerField(blank=True, null=True, verbose_name='凭据ID')),
                ('crawler_scope', models.TextField(blank=True, default='', verbose_name='爬取范围')),
                ('filter_rule', models.TextField(blank=True, default='', verbose_name='过滤规则')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '采集中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='状态')),
                ('result_msg', models.TextField(blank=True, default='', verbose_name='结果信息')),
                ('element_count', models.IntegerField(default=0, verbose_name='采集元素数')),
                ('step_count', models.IntegerField(default=0, verbose_name='生成步骤数')),
                ('auto_asset_id', models.IntegerField(blank=True, null=True, verbose_name='自动生成资产ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('create_user', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '爬取任务',
                'verbose_name_plural': '爬取任务',
                'db_table': 'kb_crawler_task',
            },
        ),
    ]
