# Generated by Django 5.2.13 on 2026-07-02 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, verbose_name='项目ID')),
                ('env_name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('env_type', models.CharField(choices=[('test', '测试'), ('staging', '预发'), ('production', '生产')], default='test', max_length=20, verbose_name='环境类型')),
                ('base_url', models.CharField(max_length=500, verbose_name='基础URL')),
                ('headers', models.TextField(blank=True, default='{}', verbose_name='请求头(JSON)')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'kb_env',
            },
        ),
        migrations.CreateModel(
            name='KbCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='凭据标题')),
                ('account', models.CharField(blank=True, default='', max_length=200, verbose_name='账号')),
                ('password', models.TextField(blank=True, default='', verbose_name='密码(加密)')),
                ('cookie', models.TextField(blank=True, default='', verbose_name='Cookie(加密)')),
                ('token', models.TextField(blank=True, default='', verbose_name='Token(加密)')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='environment.kbenv', verbose_name='环境')),
            ],
            options={
                'verbose_name': '凭据',
                'verbose_name_plural': '凭据',
                'db_table': 'kb_credential',
            },
        ),
    ]
