# Generated by Django 5.2.13 on 2026-07-02 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('project_code', models.CharField(max_length=50, unique=True, verbose_name='项目唯一编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态')),
                ('default_env_id', models.IntegerField(blank=True, null=True, verbose_name='默认关联环境ID')),
                ('default_llm_config_id', models.IntegerField(blank=True, null=True, verbose_name='默认LLM模型ID')),
                ('global_timeout', models.IntegerField(default=60, verbose_name='全局执行超时(秒)')),
                ('global_retry', models.IntegerField(default=0, verbose_name='全局重试次数')),
                ('default_priority', models.CharField(default='P2', max_length=20, verbose_name='资产默认优先级')),
                ('create_user', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'sys_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('member', '普通成员')], default='member', max_length=20, verbose_name='角色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.sysproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'db_table': 'sys_project_member',
                'unique_together': {('project', 'user_id')},
            },
        ),
    ]
