# Generated by Django 5.2.13 on 2026-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbRefluxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, verbose_name='项目ID')),
                ('asset_id', models.IntegerField(verbose_name='资产ID')),
                ('run_record_id', models.IntegerField(blank=True, null=True, verbose_name='关联执行记录ID')),
                ('reflux_type', models.CharField(choices=[('light', '轻量数据(自动回流)'), ('structural', '结构性数据(需审核)')], default='light', max_length=20, verbose_name='回流类型')),
                ('diff_content', models.TextField(blank=True, default='{}', verbose_name='差异内容(JSON)')),
                ('new_script', models.TextField(blank=True, default='', verbose_name='新脚本')),
                ('new_element_data', models.TextField(blank=True, default='{}', verbose_name='新元素数据(JSON)')),
                ('new_step_data', models.TextField(blank=True, default='[]', verbose_name='新步骤数据(JSON)')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('ignored', '已忽略'), ('failed', '回流失败')], default='pending', max_length=20, verbose_name='审核状态')),
                ('audit_user', models.CharField(blank=True, default='', max_length=100, verbose_name='审核人')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '回流记录',
                'verbose_name_plural': '回流记录',
                'db_table': 'kb_reflux_record',
                'ordering': ['-create_time'],
            },
        ),
    ]
