# Generated by Django 5.2.13 on 2026-07-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KbElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True, verbose_name='项目ID')),
                ('page_name', models.CharField(max_length=200, verbose_name='页面名称')),
                ('element_name', models.CharField(max_length=200, verbose_name='元素名称')),
                ('element_type', models.CharField(max_length=50, verbose_name='元素类型')),
                ('locator_type', models.CharField(max_length=50, verbose_name='定位器类型')),
                ('locator_value', models.CharField(max_length=500, verbose_name='定位器值')),
                ('status', models.CharField(choices=[('valid', '有效'), ('invalid', '失效')], default='valid', max_length=20, verbose_name='状态')),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True, verbose_name='最后刷新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公共元素',
                'verbose_name_plural': '公共元素',
                'db_table': 'kb_element',
            },
        ),
    ]
